### ISSUE TITLE
segmentation!

### ISSUE THREAD

**Issue by HaoranRS** [ziqi-jin/finetune-anything#8]
Issuer:'MaskDecoder' object has no attribute 'iou_head_depth'. What is the cause of this problem?

**Comment by ziqi-jin** [comment]
> Issuer:'MaskDecoder' object has no attribute 'iou_head_depth'. What is the cause of this problem?

Have you installed the official SAM before? Finetune-Anything (FA) has modified the code of the original SAM model. If the SAM you imported is official, please make sure that the imported SAM is the modified SAM model in FA. The FA modified model code is at this [line](https://github.com/ziqi-jin/finetune-anything/blob/a518d3174b470f5f8cae1b5c89332b3226cffbc0/extend_sam/segment_anything_ori/modeling/mask_decoder.py#L52)

**Comment by GesilaA** [comment]
@ziqi-jin Thank you for your owesome work! This problem is solved by replace line4 in extend_sam/extend_sam.py `from sagment_anything import sam_model_registry -> from .segment_anything_ori import sam_model_registry`
And if I want to train my dataset as resolution(1280x1280), the dim mismatch error occured: `RuntimeError: Given groups=1, weight of size [768, 3, 16, 16], expected input[4, 1280, 1280, 3] to have 3 channels, but got 1280 channels instead` Could you help me to solve this problem?

**Comment by ziqi-jin** [comment]
> 


> @ziqi-jin Thank you for your owesome work! This problem is solved by replace line4 in extend_sam/extend_sam.py `from sagment_anything import sam_model_registry -> from .segment_anything_ori import sam_model_registry` And if I want to train my dataset as resolution(1280x1280), the dim mismatch error occured: `RuntimeError: The size of tensor a (80) must match the size of tensor b (64) at non-singleton dimension 2` Could you help me to solve this problem?

Now the parameters of Finetune Anything are not connected with the model input of SAM, you may need to manually modify the initialization input of the original SAM model. Because the input of the model involves some testing problems, it has not been implemented yet, and I will fix this problem later. At the same time, if you solve this problem, you are also welcome to submit a PR

**Comment by ziqi-jin** [comment]
> @ziqi-jin Thank you for your owesome work! This problem is solved by replace line4 in extend_sam/extend_sam.py `from sagment_anything import sam_model_registry -> from .segment_anything_ori import sam_model_registry` And if I want to train my dataset as resolution(1280x1280), the dim mismatch error occured: `RuntimeError: The size of tensor a (80) must match the size of tensor b (64) at non-singleton dimension 2` Could you help me to solve this problem?

Thanks, I will test and fix the import bugs

**Comment by moonboy12138** [comment]
I've also met this problem when I tried to use the 512*512 image as input,
"RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 2",
and found the image size  is hard to modify, how can i solve this problem?

**Comment by ManuelEck** [comment]
Thanks for this amazing work!

I just tried to finetune on a custom dataset for semantic segmentation. 
For me th error:
`RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 2` 
still persist.  I can't seem to see why those tensors have a different size. 
The error accures in 
```
extend_sam/segment_anything_ori/modeling/image_encoder.py", line 111, in forward 
x = x + self.pos_embed
RuntimeError: The size of tensor a (32) must match the size of tensor b (64) at non-singleton dimension 2
```

Any insight how you were able to solve this error?

**Comment by aylinSyntonym** [comment]
I try to train my model 128x128 and I am getting similar error 

> RuntimeError: The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 2

How can I resolve problem quickly?
